### ISSUE TITLE
piping in tshell output doesn't seem to work

### ISSUE THREAD

**Issue by apella** [TatriX/tshell#4]
eg:
```
$ ls
```
\*tshell-out\*:
> LICENSE  README.md  echo  grep	sed  tshell.el	tshell.elc

Then, following the example from the readme:
```
$ > grep '.el'
```
\*tshell-out\*:
> /usr/local/bin/bash: line 1: .el: command not found

**Comment by TatriX** [comment]
Oups. Thanks for the report.
Should be fixed in 488db7f

**Comment by apella** [comment]
Yup, that fixed it! Thanks for the quick turn-around! I really like the concept of this package.

I've taken the liberty of creating a PR for something else that was broken for me.
